/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift_left_27 (
    input [15:0] a,
    input [3:0] b,
    output reg [15:0] left
  );
  
  
  
  reg [15:0] x;
  
  reg [15:0] y;
  
  reg [15:0] z;
  
  always @* begin
    
    case (b[0+0-:1])
      1'h0: begin
        x = a;
      end
      1'h1: begin
        x[1+14-:15] = a[0+14-:15];
        x[0+0-:1] = 1'h0;
      end
      default: begin
        x = a;
      end
    endcase
    
    case (b[1+0-:1])
      1'h0: begin
        y = x;
      end
      1'h1: begin
        y[2+13-:14] = x[0+13-:14];
        y[0+1-:2] = 2'h0;
      end
      default: begin
        y = x;
      end
    endcase
    
    case (b[2+0-:1])
      1'h0: begin
        z = y;
      end
      1'h1: begin
        z[4+11-:12] = y[0+11-:12];
        z[0+3-:4] = 4'h0;
      end
      default: begin
        z = y;
      end
    endcase
    
    case (b[3+0-:1])
      1'h0: begin
        left = z;
      end
      1'h1: begin
        left[8+7-:8] = z[0+7-:8];
        left[0+7-:8] = 8'h00;
      end
      default: begin
        left = z;
      end
    endcase
  end
endmodule
